export enum FIXED_LIST_ITEM_ENUM {
  FIXED_LIST_ITEM_MY_DAY = 1,
  FIXED_LIST_ITEM_IMPORTANT,
  FIXED_LIST_ITEM_PLANNED,
  FIXED_LIST_ITEM_ASSIGNED_TO_ME,
  FIXED_LIST_ITEM_TASKS,
}

export enum MY_DAY_ENUM {
  UN_ADDED_MY_DAY,
  ADDED_MY_DAY
}

export enum IMPORTANT_ENUM {
  MARKED_AS_UNIMPORTANT,
  MARKED_AS_IMPORTANT,
}

export enum COMPLETED_ENUM {
  MARKED_AS_UNCOMPLETED,
  MARKED_AS_COMPLETED,
}
